### ISSUE TITLE
Не удаётся получить количество просмотров видео

### ISSUE THREAD

**Issue by bolshakov** [Twizty/watches#1]
Запустил сервер:

```sh
> bundle exec rackup config.ru
Thin web server (v1.7.0 codename Dunder Mifflin)
Maximum connections set to 1024
Listening on localhost:9292, CTRL+C to stop
```

Отправляю один "пинг", а затем пытаюсь получить информацию о количестве просмотров этого же пользователя. В результате возвращается 500 ошибка:

```sh
> http --headers POST localhost:9292/videos/video_id_1/watch user_id=user_id_1
HTTP/1.1 201 Created
....
> http --headers GET localhost:9292/users/user_id_1/watches
HTTP/1.1 500 Internal Server Error
...
```

Лог сервера:

```sh
::1 - - [03/May/2017:09:08:05 +0300] "POST /videos/video_id_1/watch HTTP/1.1" 201 - 0.0184
2017-05-03 09:08:06 - NoMethodError - private method `select' called for nil:NilClass:
	/Users/bolshakov/Projects/tmp/watches/store/in_memory.rb:15:in `fetch'
	/Users/bolshakov/Projects/tmp/watches/app.rb:33:in `block in <class:App>'
```

**Comment by Twizty** [comment]
А какой программой отправляется запрос? Я проверяю в постмане, у меня все работает хорошо. Может быть, тело запроса не уходит? Я забыл проинициализировать пустое значение для видео, у которых нет просмотров, сейчас это исправил, но это не должно было быть проблемой в этом случае.

**Comment by bolshakov** [comment]
Упс, ошибся с синтаксисом пост параметров.  Проблема была в том, что я вообще не передал параметр `user_id`. 

Нужно было:

```sh
> http --headers POST localhost:9292/videos/video_id_1/watch user_id==user_id_1
HTTP/1.1 201 Created
```

Одно равно - передаёт header, а не POST параметр. Это [httpie](https://httpie.org).

**Comment by bolshakov** [comment]
Теперь проблема с redis адаптером.

Сервер:

```sh
✗ USE_REDIS=true bundle exec rackup config.ru
Thin web server (v1.7.0 codename Dunder Mifflin)
Maximum connections set to 1024
Listening on localhost:9292, CTRL+C to stop
::1 - - [03/May/2017:10:07:40 +0300] "POST /videos/video_id_1/watch?used_id=user_id_1 HTTP/1.1" 201 - 0.0512
::1 - - [03/May/2017:10:07:45 +0300] "GET /users/user_id_1/watches HTTP/1.1" 200 2 0.0017
```

Запросы:

```sh
> http --headers POST localhost:9292/videos/video_id_1/watch used_id==user_id_1
HTTP/1.1 201 Created

>  http GET localhost:9292/users/user_id_1/watches
[]
```

Возвращается пустой массив.

**Comment by Twizty** [comment]
@bolshakov когда запрос отправляется так, в приложении тело оказывается пустым. Пытаюсь понять, в чем проблема. В других http-клиентах работает. Например `curl --data "user_id=user_id_1" localhost:9292/videos/video_id_1/watch` работает отлично.

**Comment by bolshakov** [comment]
Ох, какой я невнимательный - опять опечатался:

```sh
> http POST localhost:9292/videos/video_id_1/watch used_id==user_id_1
> http POST localhost:9292/videos/video_id_1/watch user_id==user_id_1
```

**Comment by Twizty** [comment]
@bolshakov я вот только что это нашел, но тоже в упор не видел очепятки.
